language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install -r requirements.txt
    - pip install pytest pytest-mock pytest-cov coveralls
script:
    - py.test clok -v --cov clok --cov-report term-missing
after_success:
    - coveralls
