language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install 'pytest>=2.7' pytest-mock pytest-cov coveralls
    - pip install -r requirements.txt
script:
    - py.test clok -v --cov clok --cov-report term-missing
after_success:
    - coveralls
