language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
install:
    - pip install -r requirements.txt
    - pip install tox pytest pytest-mock pytest-cov coveralls
script:
    - tox -e $TOX_ENV
    - if [[ $TOX_ENV == py27 ]]; then
          py.test --cov-report term-missing --cov clok clok;
      fi
after_success:
    - if [[ $TOX_ENV == py27 ]]; then
          coveralls;
      fi
